version: "3"

networks:
  sonar_practice_network:
    driver: bridge

volumes:
  sonarqube_data:

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - sonar_practice_network
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_DATA=/var/sonarqube/data
    volumes:
      - ./sonarqube_data:/var/sonarqube/data

  # test-app:
